// Ordered so the most emotionally resonant, life-experience categories surface
// first in the explore filter bar and write-page picker — these are what make
// Lekhsetu feel like real human stories rather than a generic blog.
export const CATEGORIES = [
  { id: "firstjob",        label: "First Job",          emoji: "🧑‍💼", color: "#15803d" },
  { id: "failure",         label: "Failure & Comeback", emoji: "🔁", color: "#65a30d" },
  { id: "layoff",          label: "Layoffs & Job Loss", emoji: "📉", color: "#b91c1c" },
  { id: "studentlife",     label: "Student Life",       emoji: "🏫", color: "#2563eb" },
  { id: "success",         label: "Success Stories",    emoji: "🏆", color: "#ca8a04" },
  { id: "startup",         label: "Startup Life",       emoji: "🏗️", color: "#3730a3" },
  { id: "heartbreak",      label: "Heartbreak",         emoji: "💔", color: "#9f1239" },
  { id: "marriage",        label: "Marriage",           emoji: "💍", color: "#c026d3" },
  { id: "parenting",       label: "Parenting",          emoji: "👶", color: "#f59e0b" },
  { id: "relationships",   label: "Relationships",      emoji: "❤️", color: "#dc2626" },
  { id: "love",            label: "Love & Romance",     emoji: "💞", color: "#db2777" },
  { id: "friendship",      label: "Friendship",         emoji: "🤝", color: "#0d9488" },
  { id: "family",          label: "Family",             emoji: "👨‍👩‍👧", color: "#b45309" },
  { id: "immigration",     label: "Immigration",        emoji: "🌍", color: "#0e7490" },
  { id: "army",            label: "Defence & Armed Forces", emoji: "🎖️", color: "#4d7c0f" },
  { id: "confessions",     label: "Confessions",        emoji: "🤫", color: "#6d28d9" },
  { id: "motivation",      label: "Motivation",         emoji: "🔥", color: "#ea4335" },
  { id: "selfimprovement", label: "Self Improvement",   emoji: "📈", color: "#059669" },
  { id: "mentalhealth",    label: "Mental Health",      emoji: "🧠", color: "#7c3aed" },
  { id: "life",            label: "Life Lessons",       emoji: "🌱", color: "#e8751a" },
  { id: "nostalgia",       label: "Nostalgia",          emoji: "🕰️", color: "#a8a29e" },
  { id: "smalltown",       label: "Small Town Stories", emoji: "🏡", color: "#a16207" },
  { id: "women",           label: "Women's Stories",    emoji: "👩", color: "#e11d48" },
  { id: "lgbtq",           label: "LGBTQ+ Stories",     emoji: "🌈", color: "#9333ea" },
  { id: "socialissues",    label: "Social Issues",      emoji: "⚖️", color: "#475569" },
  { id: "entrepreneurship",label: "Entrepreneurship",   emoji: "🚀", color: "#4338ca" },
  { id: "job",             label: "Job Search",         emoji: "🧳", color: "#0f766e" },
  { id: "career",          label: "Career",            emoji: "💼", color: "#1a6b5e" },
  { id: "health",          label: "Wellbeing",          emoji: "🧘", color: "#9333ea" },
  { id: "education",       label: "Education",          emoji: "🎓", color: "#1d4ed8" },
  { id: "exams",           label: "Exam Journeys",      emoji: "📝", color: "#0891b2" },
  { id: "travel",          label: "Travel",             emoji: "✈️", color: "#0284c7" },
  { id: "culture",         label: "Culture & Tradition",emoji: "🪔", color: "#ea580c" },
  { id: "spirituality",    label: "Spirituality",       emoji: "🙏", color: "#a16207" },
  { id: "finance",         label: "Finance",            emoji: "💰", color: "#16a34a" },
  { id: "knowledge",       label: "Knowledge",          emoji: "📚", color: "#7a5c2e" },
  { id: "tech",            label: "Technology",         emoji: "⚡", color: "#2563eb" },
  { id: "science",         label: "Science",            emoji: "🔬", color: "#0369a1" },
  { id: "history",         label: "History",            emoji: "🏺", color: "#78350f" },
  { id: "politics",        label: "Politics",           emoji: "🏛️", color: "#374151" },
  { id: "nature",          label: "Nature & Environment", emoji: "🌿", color: "#16a34a" },
  { id: "sports",          label: "Sports",             emoji: "🏅", color: "#d97706" },
  { id: "art",             label: "Art & Creativity",   emoji: "🎨", color: "#be185d" },
  { id: "music",           label: "Music",              emoji: "🎵", color: "#7e22ce" },
  { id: "writing",         label: "Writing & Poetry",   emoji: "✍️", color: "#92400e" },
  { id: "books",           label: "Books & Reading",    emoji: "📖", color: "#854d0e" },
  { id: "cinema",          label: "Cinema & Entertainment", emoji: "🎬", color: "#9333ea" },
  { id: "food",            label: "Food & Cooking",     emoji: "🍲", color: "#c2410c" },
  { id: "fashion",         label: "Fashion & Style",    emoji: "👗", color: "#db2777" },
  { id: "fiction",         label: "Fiction & Stories",  emoji: "📜", color: "#44403c" },
];

// Maps an Indian state/region name (as commonly returned by reverse-geocoding
// services) to the language code readers there are most likely to prefer —
// used to auto-show the matching translation of a multi-language story.
export const STATE_LANGUAGE_MAP: Record<string, string> = {
  "andhra pradesh": "te",
  "telangana": "te",
  "tamil nadu": "ta",
  "puducherry": "ta",
  "karnataka": "kn",
  "kerala": "ml",
  "lakshadweep": "ml",
  "maharashtra": "mr",
  "goa": "mr",
  "west bengal": "bn",
  "punjab": "pa",
  "chandigarh": "pa",
  "gujarat": "gu",
  "dadra and nagar haveli and daman and diu": "gu",
  "odisha": "or",
  "assam": "as",
  "jammu and kashmir": "ur",
  "ladakh": "ur",
  "delhi": "hi",
  "uttar pradesh": "hi",
  "bihar": "hi",
  "madhya pradesh": "hi",
  "rajasthan": "hi",
  "haryana": "hi",
  "jharkhand": "hi",
  "chhattisgarh": "hi",
  "uttarakhand": "hi",
  "himachal pradesh": "hi",
};

// English + all 22 languages of the Indian Constitution's Eighth Schedule,
// plus a few major international languages for global readers.
export const LANGUAGES = [
  { code: "en", label: "English",    native: "English"          },
  { code: "hi", label: "Hindi",      native: "हिंदी"            },
  { code: "bn", label: "Bengali",    native: "বাংলা"            },
  { code: "mr", label: "Marathi",    native: "मराठी"            },
  { code: "te", label: "Telugu",     native: "తెలుగు"           },
  { code: "ta", label: "Tamil",      native: "தமிழ்"           },
  { code: "gu", label: "Gujarati",   native: "ગુજરાતી"          },
  { code: "ur", label: "Urdu",       native: "اردو"             },
  { code: "kn", label: "Kannada",    native: "ಕನ್ನಡ"            },
  { code: "or", label: "Odia",       native: "ଓଡ଼ିଆ"            },
  { code: "ml", label: "Malayalam",  native: "മലയാളം"          },
  { code: "pa", label: "Punjabi",    native: "ਪੰਜਾਬੀ"          },
  { code: "as", label: "Assamese",   native: "অসমীয়া"          },
  { code: "mai", label: "Maithili",  native: "मैथिली"           },
  { code: "sat", label: "Santali",   native: "ᱥᱟᱱᱛᱟᱲᱤ"          },
  { code: "ks", label: "Kashmiri",   native: "کٲشُر"            },
  { code: "ne", label: "Nepali",     native: "नेपाली"           },
  { code: "gom", label: "Konkani",   native: "कोंकणी"           },
  { code: "sd", label: "Sindhi",     native: "سنڌي"             },
  { code: "doi", label: "Dogri",     native: "डोगरी"            },
  { code: "mni", label: "Manipuri",  native: "মৈতৈলোন্"        },
  { code: "brx", label: "Bodo",      native: "बड़ो"             },
  { code: "sa", label: "Sanskrit",   native: "संस्कृतम्"        },
  { code: "ar", label: "Arabic",     native: "العربية"          },
  { code: "fr", label: "French",     native: "Français"         },
  { code: "es", label: "Spanish",    native: "Español"          },
  { code: "de", label: "German",     native: "Deutsch"          },
  { code: "pt", label: "Portuguese", native: "Português"        },
  { code: "id", label: "Indonesian", native: "Bahasa Indonesia" },
  { code: "sw", label: "Swahili",    native: "Kiswahili"        },
];
